.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Add PULL REQUEST TEMPLATE and CHANGELOG
=> Add PULL REQUEST TEMPLATE and CHANGELOG

CHANGELOG.md, manifest.json, store/blocks/product/blocks/appFeatures.jsonc, store/blocks/product/blocks/appOverview.jsonc, styles/css/product/vtex.app-store-components.css
Add new features and overview format
[Workspace](https://pricenew--extensions.myvtex.com/lengow/p?cultureInfo=en-US)
=> Add new features and overview format

CHANGELOG.md, store/blocks/all-apps/index.json, store/blocks/home/index.jsonc, store/blocks/search-bar/index.jsonc
Add search bar to the home page
[Workspace](https://newhome--extensions.myvtex.com/)
=> Add search bar to the home page

CHANGELOG.md, store/blocks/home/blocks/bottomCards.jsonc, store/blocks/home/blocks/categories.jsonc, store/blocks/home/blocks/infocard.jsonc, store/blocks/home/blocks/mostUsed.jsonc
Adjust Home content
[Workspace](https://pricenew--extensions.myvtex.com/)
=> Adjust Home content

CHANGELOG.md, store/blocks/product/blocks/appAdditionalInformation.jsonc, store/blocks/product/blocks/appFeatures.jsonc, store/blocks/product/blocks/appOverview.jsonc, store/blocks/product/blocks/appPricing.jsonc, store/blocks/product/blocks/appScreenshots.jsonc, store/blocks/product/blocks/navBar.jsonc, store/blocks/product/blocks/sideBar.jsonc, store/blocks/product/blocks/specifications.jsonc, store/blocks/product/blocks/topBar.jsonc, store/blocks/product/index.jsonc, styles/css/product/vtex.breadcrumb.css, styles/css/product/vtex.flex-layout.css, styles/css/product/vtex.product-specification-badges.css
- `Major` specification
- `additionalInformation` specification
- `PDP` container, margins
[Workspace](https://pricenew--extensions.myvtex.com/vtex-google-customer-reviews/p)
=> Pdp desktop adjusts

CHANGELOG.md, manifest.json, store/blocks/home/blocks/bottomCards.jsonc, store/blocks/product/index.jsonc, styles/css/home/vtex.store-link.css, styles/css/product/vtex.app-store-components.css, styles/css/product/vtex.app-store-price.css, styles/css/product/vtex.breadcrumb.css, styles/css/product/vtex.flex-layout.css, styles/css/product/vtex.rich-text.css, styles/css/product/vtex.store-components.css
Pdp adjusts (Font size, Image size, breadcrumb,  spaces) 
[Workspace](https://pricenew--extensions.myvtex.com/vtex-sms-provider/p)
=> Pdp adjusts (Font size, Image size, breadcrumb,  spaces) 

store/blocks/all-apps/blocks/allappsbottom.json, store/blocks/all-apps/index.json, styles/css/all-apps/vtex.flex-layout.css, styles/css/search/vtex.flex-layout.css, styles/css/vtex.store-components.css
Adjusted content on bottom cards of all apps
[Workspace](https://savio--extensions.myvtex.com/)
=> Fixed all apps content on bottom and paddings

store/blocks/not-found/index.jsonc, store/blocks/product/index.jsonc, store/blocks/search-bar/index.jsonc, store/routes.json
Search adjustments
[Workspace](https://newhome--extensions.myvtex.com/)
=> Search adjustments

store/blocks/home/blocks/bottomCards.jsonc, styles/css/home/vtex.flex-layout.css, styles/css/home/vtex.store-components.css
Adjust Bottom Cards Desktop
[Workspace](https://pricenew--extensions.myvtex.com/)
=> Adjust Bottom Cards Desktop

styles/css/search/vtex.flex-layout.css
Width fixed on search
[Workspace](url)
=> fixed width for search bug

CHANGELOG.md, store/blocks/home/blocks/bottomCards.jsonc, styles/css/home/vtex.store-components.css
Fixed alignment on bottom cards
[Workspace](https://savio--extensions.myvtex.com/all-apps)
=> Fix bottom cards image alignment

store/blocks/not-found/index.jsonc, store/blocks/product/index.jsonc
Fix 404
[Workspace](https://newhome--extensions.myvtex.com/)
=> fix search

store/blocks/product/blocks/mobile/index.jsonc, store/blocks/product/blocks/mobile/specifications/index.jsonc, store/blocks/product/blocks/topBar.jsonc, store/blocks/product/index.jsonc, styles/css/product/extensions.account-dialog.css, styles/css/product/vtex.flex-layout.css, styles/css/product/vtex.store-components.css
First version: PDP mobile.
[Workspace](https://pricenew--extensions.myvtex.com/vtex-google-shopping/p)
=> PDP mobile

store/blocks/home/blocks/categories.jsonc, store/blocks/search/blocks/layout.jsonc, styles/css/home/vtex.store-link.css
Related PR: https://github.com/vtex-apps/store-link/pull/18
Test here: http://anchor--extensions.myvtex.com/
=> Fixing anchor link, not-found layout and button turning blue

store/blocks/search-bar/index.jsonc
=> remove search custom label

store/blocks/all-apps/blocks/categories.json, store/blocks/home/blocks/mostUsed.jsonc, store/blocks/home/index.jsonc, store/blocks/product/blocks/sideBar.jsonc, store/blocks/search-bar/index.jsonc, store/blocks/search/index.jsonc
=> Performance

store/blocks/all-apps/blocks/categories.json, store/blocks/home/blocks/mostUsed.jsonc, store/blocks/search-bar/index.jsonc, store/blocks/search/index.jsonc
=> remove perf search otptimizations

CHANGELOG.md, store/blocks/footer.jsonc, store/blocks/home/blocks/bottomCards.jsonc, store/blocks/home/blocks/infocard.jsonc, styles/css/home/vtex.flex-layout.css, styles/css/vtex.store-link.css
To fix links and padding of home page
[Workspace](http://savio--extensions.myvtex.com/)
=> links and padding

CHANGELOG.md, store/blocks/product/blocks/sideBar.jsonc, styles/css/product/vtex.product-specification-badges.css, styles/css/product/vtex.rich-text.css
Add .x after major
[Workspace](https://pricenew--extensions.myvtex.com/vtex-sms-provider/p)
=> Add .x after major

CHANGELOG.md, manifest.json, store/blocks/terms-of-service/index.jsonc
To add a terms of service layout
[Workspace](https://savio--extensions.myvtex.com/terms-of-service)
=> added terms of service page

CHANGELOG.md, store/blocks/all-apps/blocks/categories.json, store/blocks/all-apps/index.json
Add storeDesign category and update Logistics category description
[Workspace](https://pricenew--extensions.myvtex.com/all-apps)
=> Add storeDesign category and update Logistics category description

CHANGELOG.md, store/blocks/header.jsonc, store/blocks/home/blocks/bottomCards.jsonc, store/blocks/product/blocks/appScreenshots.jsonc, store/blocks/product/blocks/mobile/index.jsonc, store/blocks/product/index.jsonc, styles/css/all-apps/vtex.flex-layout.css, styles/css/home/vtex.flex-layout.css, styles/css/home/vtex.store-components.css, styles/css/product/extensions.account-dialog.css, styles/css/product/vtex.app-store-components.css, styles/css/product/vtex.flex-layout.css, styles/css/product/vtex.store-components.css, styles/css/vtex.menu.css
Fix tablet layout and carrousel
[Workspace](https://pricenew--extensions.myvtex.com/)
=> Fix tablet layout and carrousel

CHANGELOG.md, store/blocks/home/blocks/highlights.jsonc, store/blocks/home/index.jsonc
This PR is adding a new shelf on the home page
[Testar aqui](https://highlight--extensions.myvtex.com/)
=> adds a highlights shelf on the home page

CHANGELOG.md, styles/css/search/vtex.search.css
Do not show product price in autocomplete result (mobile / tablet)
[Workspace](https://pedrofix--extensions.myvtex.com/)
=> Do not show product price in autocomplete result (mobile and tablet)

CHANGELOG.md, store/blocks/header.jsonc, styles/css/vtex.app-store-components.css, styles/css/vtex.locale-switcher.css
This adds an indicator/switcher to the store's sales channels
Visit this [workspace](https://artur--extensions.myvtex.com/)
=> Add store selector to the theme header

CHANGELOG.md, store/blocks/home/blocks/newApps.jsonc, store/blocks/home/index.jsonc
Shelf new apps by Manoel
[Workspace](https://newappshome--extensions.myvtex.com/)
=> shelf new apps

CHANGELOG.md, manifest.json
=> Release v0.33.0

CHANGELOG.md, manifest.json
=> Release v0.35.1

CHANGELOG.md, manifest.json
Releases https://github.com/vtex-apps/app-store-theme/pull/152
[Workspace](https://appstorelogin--extensions.myvtex.com/vtex-reviews-and-ratings/p?__bindingAddress=extensions.myvtex.com/)
None
=> Release v1.0.0

CHANGELOG.md, store/blocks/header.jsonc, styles/css/vtex.app-store-components.css, styles/css/vtex.locale-switcher.css
Replace current login component by [this new one](https://github.com/vtex-apps/app-store-components/pull/26).
Visit this [workspace](https://apps.vtex.com?workspace=appstorelogin) and click `LOGIN` in the upper-right corner.
None
=> Use new login menu

CHANGELOG.md, store/blocks/product/blocks/mobile/index.jsonc, store/blocks/product/index.jsonc
Depends on:  https://github.com/vtex-apps/app-store-components/pull/29
PS: The build fails due to this dependency
=> Adds compatibility alert component to Product page

CHANGELOG.md, manifest.json
=> Release v1.3.1

CHANGELOG.md, manifest.json, messages/en.json, messages/es.json, messages/pt.json, react/NotFoundBox.tsx, react/global.module.css, store/blocks/not-found/index.jsonc, store/interfaces.json
Updates 404 page
[Workspace](http://fox3--extensions.myvtex.com/vtexdaga-tawk-to/p?__bindingAddress=extensions.myvtex.com/)
=> Feature: 404 page

CHANGELOG.md, manifest.json, store/blocks/checkout/index.jsonc, store/blocks/product/blocks/mobile/index.jsonc
[Workspace](https://fox3--extensions.myvtex.com/)
1. Enter https://apps.vtex.com/vtex-sms-provider/p?wokspace=fox3
2. Click get App (Login to `fashion2`)
3. When in checkout you should see the alert
Warn example:
PS: This is a mock to showcase another behavior for the alert
Inform example:
PS: This is a mock to showcase another behavior for the alert
Block example:
=> Adds compatibility alert to checkout
